### PR TITLE
Cleaning + currency sharing feature

### PR DESCRIPTION
**Pull request by Daimakaicho**
* add linter (standard javascript)
 * fix all lint error
 * clean some jsdoc
 * remove all .mjs extension to help with reverse proxy
 #52

### CODE REVIEW

**Comment by Daimakaicho** [comment]
* fix images not loaded in compendiums when better-rolltables is enabled 
#113

**Comment by Daimakaicho** [comment]
* fix text results handled as items when using new tables mode
#114

**Comment by Daimakaicho** [comment]
* fix broken result icon when result is a macro
#111

**Comment by Daimakaicho** [comment]
* add new currency sharing feature (optional as always)
share-currency

**Review by ultrakorne — APPROVED** [review]

**Pull request merged**
