### PR TITLE
Fixes: Spell scroll, table from Compendium

### LINKED ISSUE #77: betterTables.createTableFromCompendium does work
Self-explanatory, the api to generate tables is not working in v.8.x

### LINKED ISSUE #84: Broken Inline Rolls on Loot Table
Using an inline roll in a text entity of a loot table no longer works. It is failing in multiple ways:
1. It breaks the text apart at the inline roll. Anything that comes after that inline roll is no longer a part of the item; and
2. It throw an error saying "no table named <inline roll formula> found in compendium.

Using a book with "volumes" as an example, previously it would have displayed like this (with everything within the brackets part of the item name) {Some Book Vol. <roll result>: Additional Text}. 

Now it looks like this:

Here is the table and the error about compendiums:

### PR DESCRIPTION
**Pull request by DanielBoettner**
Fixed generation of spellscrolls.

The way the indexes are generated in 0.8.x is different from before.
Had to change calls from array checks to mpa checks.

* Also update spell name in the spellscroll again
* Add link and description of spell to the spell scrolls
* Updated the method to generate tables from a compendium
* Added an entry to the contextmenu of a compendium to start generation
* Fixes inline rolls like `Lorem ipsum got [[3d6]] of dolor sit amet` 
* Adds German translation

- Fixes #84
- Fixes #77

### CODE REVIEW

**Comment by DanielBoettner** [comment]
A change for inline rolls got lost.
Did it again in this Branch/PR.

**Comment by DanielBoettner** [comment]
fixes #84

**Comment by DanielBoettner** [comment]
This fixes #84

**Review by ultrakorne — APPROVED** [review]
looks good

**Pull request merged**
